routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\StudentController;
use App\Models\Student;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', function () {
    return view('auth.login');
})->name('login')->middleware('guest');


Route::get('/', function () {
    return view('welcome');
});

Route::post('authenticate', [LoginController::class, 'authenticate'])->name('authenticate');

Route::post('logout', [LoginController::class, 'logout'])->name('logout');




Route::resource('pelajar', StudentController::class)->middleware('auth');

// Route::resource('senarai-pelajar', StudentController::class)->names([
//     'index' => 'pelajar.index',
//     'create' =>'pelajar.create',
//     'store' =>'pelajar.store',
  
// ]);

Route::get('ibubapa', [StudentController::class, 'editIbuBapa'])->name('maklumat.ibubapa');


// Route::get('pelajar', [StudentController::class, 'index'])->name('pelajar.senarai');

// Route::post('pelajar', [StudentController::class, 'store'])->name('pelajar.store');

// Route::get('pelajar/{id}', [StudentController::class, 'edit'])->name('pelajar.edit');

// Route::put('pelajar/{id}', [StudentController::class, 'update'])->name('pelajar.update');
// Route::delete('pelajar/{id}', [StudentController::class, 'update'])->name('pelajar.delete');


Route::get('dwonloadfile/{id}', function ($id) {
    
    $data=Student::find($id);

    return Storage::download($data->ic_path);
})->name('downloadfile');


Route::get('download-path', function (Request $request) {
   $path= $request->path;
    return Storage::download($path);
})->name('download.path');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * @property integer $id
 * @property integer $id_school
 * @property integer $id_level
 * @property string $name_student
 * @property string $ic
 * @property string $address
 * @property string $created_at
 * @property string $updated_at
 * @property Lookup $lookup
 * @property Lookup $lookup
 */
class Student extends Model
{
  
    use  SoftDeletes;
    /**
     * The "type" of the auto-incrementing ID.
     * 
     * @var string
     */
    protected $keyType = 'integer';

    /**
     * @var array
     */
    protected $fillable = ['ic_path','id_school', 'id_level', 'name_student', 'ic', 'address', 'created_at', 'updated_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function lookupLevel()
    {
        return $this->belongsTo('App\Models\Lookup', 'id_level');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function lookupSchool()
    {
        return $this->belongsTo('App\Models\Lookup', 'id_school');
    }


    public function scopeMaster($query)
    {
        // return $query->where('type', $type);
    }

    
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Lookup;
use App\Models\Student;

use App\Models\SijilFile;
use App\Mail\StandardEmail;
use Illuminate\Http\Request;

use App\Helpers\BankStatusHelper;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       
        // dd($request);

        // dd($request);
       $school =Lookup::where(['code'=>'002','category'=>'school'])->first();

       $data=Lookup::where(['category'=>'school'])->get();

       $lookupSchool=$data->pluck('name','id');

       

       $student= Student::with(['lookupLevel','lookupSchool']);
       
  

       if($request->name_student){
        $student->where('name_student', 'like', "%$request->name_student%");
       }

       if($request->id_school){
        $student->where(['id_school'=>$request->id_school]);
       }
     

       

       $students=$student->paginate(10);

      


      $lookupSchool= BankStatusHelper::getSchool();

    


        return view('student.index',compact('students','lookupSchool'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $d['url']=route('pelajar.store');

        $d['lookupSchool']= BankStatusHelper::getSchool();
        $d['lookupLevel']= BankStatusHelper::getLevel();
        $d['student']=new student();

        $d['mode']='store';


        return view('student.create',$d);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      
        // $filename='pelajar001.pdf';
        // $path='noic/sijil';
        

        // $pathnew = $request->file('sijil_pmr')->storeAs($path,$filename);
       
        //  $bil=1;
        

        // foreach($request->sijil_spm as $row){

        //     $filename='pelajartest'.++$bil.'.pdf';
          

        //     $pathnew = $row->storeAs($path,$filename);

        //     print_r($pathnew);
        // }


        
        // dd($path);

        $message=[
            'name_student.required'=>'sila isi nama pelajar'
        ];


            $validate=$request->validate([
                'name_student'=>'required',
                'ic'=>'required|unique:students,ic',
                'address'=>'required',
                'id_school'=>'required',
                'id_level'=>'required',
                'sijil_pmr'=>'required|file|mimes:pdf',
                
            ],$message);


            if($request->file('sijil_pmr')){

                $time=time();
            
            $extensionic = $request->file('sijil_pmr')->extension();
            $filename='ic_'.$time.'.'. $extensionic; 
            $path=$request->noic.'/ic';

            if($pathnew = $request->file('sijil_pmr')->storeAs($path,$filename)){
                $validate['ic_path']=$pathnew;
            }

            }

          

            // $id_staff=  Auth::id();
            
            //  $validate['umur']=$request->umur;

        //     $status= $request->status;

        //    $idstatus= Status::where(p['code'=>$status])->first();

           
     
        //         $validate['id_status']=$idstatus->id;

           
     

           

            if($data=Student::create($validate)){

                $pelajar=$data->id;


                if($request->file('sijil_pmr')){

                   
                
                $extensionic = $request->file('sijil_pmr')->extension();
                $filename='ic_'.$data->id.'.'. $extensionic; 
                $path=$request->noic.'/ic';
    
                if($pathnew = $request->file('sijil_pmr')->storeAs($path,$filename)){
            
                    $data->ic_path=$pathnew;

                    $data->save();

                }
    
                }



                // foreach($request->sijil_spm as $row){

                //     $extension = $row->extension();

                //     $filename='sijilspm'.$pelajar.'.'.$extension;
                    
                //     $path=$data->ic.'/'.'sijil/'.date('Y');
        
                   

                //     if($pathnew = $row->storeAs($path,$filename)){

                //         $SijilFile= new SijilFile();

                //             $SijilFile->file_name=$filename;
                //             $SijilFile->file_location=$pathnew;
                //             $SijilFile->category='sijil spm';
                //             $SijilFile->id_reference=$data->id;


                //             $SijilFile->save();

                        


                //     }


        
                   
                // }
        

                   
                return redirect()->route('pelajar.show',['pelajar'=>$pelajar])
                        ->with('success','Pelajar Telah di Tambah');

            }else{
                return redirect()->route('pelajar.index')
                        ->with('success','Pelajar Tidak Berjaya Ditambah');
            }

      
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $d['student']=Student::find($id);



        $data['title']='Pengguna cc';
        $data['student']=$d['student'];
        $userEmail='test@teet.com';

        $attach=asset('/stisla/assets/img/avatar/avatar-1.png');
       
 Mail::to($userEmail)->cc(['sukor@tets.com','test@test.com'])
 ->send(new StandardEmail('email.hantaremail', 
        $data,$attach));


        return view('student.show',$d);
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
     
        $d['url']=route('pelajar.update',['pelajar'=>$id]);
        $d['lookupSchool']= BankStatusHelper::getSchool();
        $d['lookupLevel']= BankStatusHelper::getLevel();

        $d['student']=Student::find($id);

        $d['mode']='update';

        return view('student.edit',$d);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate=$request->validate([
            'name_student'=>'required',
            'ic'=>'required|unique:students,ic,'.$id.'id',
            'address'=>'required',
            'id_school'=>'required',
            'id_level'=>'required',
        ]);

    

        $data=Student::where(['id'=>$id]);

        if($request->file('sijil_pmr')){

            $time=time();
        
        $extensionic = $request->file('sijil_pmr')->extension();
        $filename='ic_'.$time.'.'. $extensionic; 
        $path=$request->noic.'/ic';

        if($pathnew = $request->file('sijil_pmr')->storeAs($path,$filename)){
            $validate['ic_path']=$pathnew;
        }

        }


        if($data->update($validate)){

            return redirect()->route('pelajar.show',['pelajar'=>$id])
            ->with('success','Pelajar Telah dikemaskini');

        }else{

            dd('test');
        }


        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Student::find($id)->delete();
  
        return redirect()->route('pelajar.index')
                        ->with('success','Pelajar Telah di Delete');
    }


    public function editIbuBapa()
    { 
        $total=1+1;

        echo $total;


        
    }

     

}

resources/views/student/_form.blade.php
<form action="{{ $urlform }}" method="post" enctype="multipart/form-data">
    @method('put')
    @csrf
    <div class="card-body">

        <div class="form-group row">
            <label for="id_name_student" class="col-sm-3 col-form-label">Nama</label>
            <div class="col-sm-9">
                <input value='{{ old('name_student',$student->name_student??'') }}' name='name_student' type="text"
                    class="form-control @error('name_student') is-invalid @enderror" id="id_name_student"
                    placeholder="Email">
                @error('name_student')
                <div class='invalid-feedback'>{{ $message }}</div>
                @enderror

            </div>
        </div>

        <div class="form-group row">
            <label for="id_ic" class="col-sm-3 col-form-label">IC</label>
            <div class="col-sm-9">
                <input value='{{ old('ic',$student->ic??'') }}' name='ic' type="text" class="form-control"
                    id="id_ic" placeholder="Email">
            </div>
        </div>

        <div class="form-group row">
            <label for="address" class="col-sm-3 col-form-label">Alamat</label>
            <div class="col-sm-9">
                <textarea class="form-control" name="address" id="address" cols="30"
                    rows="10">{{ old('address',$student->address??'') }}</textarea>

                {{-- <input value='{{ old('address',$student->address??'') }}' name='address' type="text"
                class="form-control" id="address" placeholder="Email"> --}}
            </div>
        </div>

        <div class="form-group row">
            <label for="id_school" class="col-sm-3 col-form-label">Sekolah</label>
            <div class="col-sm-9">
                <select name='id_school' class="form-control" id="id_school">
                    <option value="" selected>Sila Pilih</option>
                    @if ($lookupSchool??'')
                    @foreach ($lookupSchool as $idsc=>$school)
                    <option {{ old('id_school',$student->id_school??'')==$idsc?'Selected':'' }} value="{{ $idsc }}">
                        {{ $school }}</option>
                    @endforeach

                    @endif
                </select>
            </div>
        </div>


        <div class="form-group row">
            <label for="id_level" class="col-sm-3 col-form-label">Tahap</label>
            <div class="col-sm-9">
                <select name='id_level' class="form-control" id="id_level">
                    <option value="" selected>Sila Pilih</option>
                    @if ($lookupLevel??'')
                    @foreach ($lookupLevel as $idlvl=>$level)
                    <option {{ old('id_level',$student->id_level??'')==$idlvl?'Selected':'' }} value="{{ $idlvl }}">
                        {{ $level }}</option>
                    @endforeach

                    @endif
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="address" class="col-sm-3 col-form-label">sijil upsr</label>
            <div class="col-sm-9">
                <div class="custom-file">
                    <input name='sijil_pmr' type="file" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <div>
                @if ($student->ic_path)

                <a href="{{ route('downloadfile',['id'=>$student->id]) }}">download by id</a>
                <br>

                <a href="{{ route('download.path',['path'=>$student->ic_path]) }}">download by path</a>

                

                @endif
              </div>
            </div>
        </div>




    </div>

    @if ( $mode=='store')
    <div class="card-footer text-center">
        <button type="submit" class="btn btn-primary">Simpan</button>
    </div>
    @elseif($mode=='update')
    <div class="card-footer text-center">
        <button type="submit" class="btn btn-primary">Kemaskini</button>
    </div>
    @endif


   
</form>



@section('scripts')
<script>
$(document).on('change', '.custom-file-input', function() {

 var fileName = $(this).val().split("\\").pop();
 $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});

</script>

 
@section('scripts')

<script>



$( document ).ready(function() {

 $( ".btnSubmitStudent" ).click(function(e) {

   e.preventDefault();

   var form=$( "#fromstudent" );

 var status=  $(this).data('status');

 var input = $("<input>")
              .attr("type", "hidden")
              .attr("name", "status").val(status);
              form.append(input);


   Swal.fire({
 title: 'Do you want to save the changes?',
 showDenyButton: true,
 showCancelButton: true,
 confirmButtonText: 'Save',
 denyButtonText: `Don't save`,
}).then((result) => {
 /* Read more about isConfirmed, isDenied below */
 if (result.isConfirmed) {

      
     Swal.fire({
      
       icon: 'info',
       title: 'sila tunggun',
       showConfirmButton: false,
    
     })

   form.submit();
 } else if (result.isDenied) {
   Swal.fire('Changes are not saved', '', 'info')
 }
})

  

});


});
</script>



   
@endsection

resources/views/student/create.blade.php
@extends('layouts.app')


@section('content')

<div class="card">
  <div class="card-header">
    <h4>Horizontal Form</h4>
  </div>
  @php
      print_r($errors->all());
  @endphp


@include('student._form');

  @endsection

resources/views/student/createold.blade.php
@extends('layouts.app')


@section('content')

<div class="card">
  <div class="card-header">
    <h4>Horizontal Form</h4>
  </div>
  @php
      print_r($errors->all());
  @endphp


  <form id='fromstudent' action="{{ route('pelajar.store') }}" method="post" enctype="multipart/form-data">
    @csrf
  <div class="card-body">

    <div class="form-group row">
      <label for="id_name_student" class="col-sm-3 col-form-label">Nama</label>
      <div class="col-sm-9">
        <input   value='{{ old('name_student') }}' name='name_student' type="text" 
        class="form-control @error('name_student') is-invalid @enderror"
         id="id_name_student"
         placeholder="Email">
        @error('name_student')
            <div class='invalid-feedback'>{{ $message }}</div>
        @enderror

      </div>
    </div>

    <div class="form-group row">
      <label for="id_ic" class="col-sm-3 col-form-label">IC</label>
      <div class="col-sm-9">
        <input  name='ic' type="text" class="form-control" id="id_ic" placeholder="Email">
      </div>
    </div>

    <div class="form-group row">
      <label for="address" class="col-sm-3 col-form-label">Alamat</label>
      <div class="col-sm-9">
        <input  name='address' type="text" class="form-control" id="address" placeholder="Email">
      </div>
    </div>

    <div class="form-group row">
      <label for="id_school" class="col-sm-3 col-form-label">Sekolah</label>
      <div class="col-sm-9">
        <select name='id_school' class="form-control" id="id_school">
          <option value="" selected>Sila Pilih</option>
          @if ($lookupSchool??'')
          @foreach ($lookupSchool as $idsc=>$school)
          <option value="{{ $idsc }}">{{ $school }}</option>
          @endforeach

          @endif
      </select>
      </div>
    </div>

    
    <div class="form-group row">
      <label for="id_level" class="col-sm-3 col-form-label">Tahap</label>
      <div class="col-sm-9">
        <select name='id_level' class="form-control" id="id_level">
          <option value="" selected>Sila Pilih</option>
          @if ($lookupLevel??'')
          @foreach ($lookupLevel as $idlvl=>$level)
          <option value="{{ $idlvl }}">{{ $level }}</option>
          @endforeach

          @endif
      </select>
      </div>
    </div>


 <div class="form-group row">
      <label for="address" class="col-sm-3 col-form-label">sijil spm</label>
      <div class="col-sm-9">
        <div class="custom-file">
          <input multiple  name='sijil_spm[]' type="file" class="custom-file-input" id="customFile">
          <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
      </div>
    </div>

    <div class="form-group row">
      <label for="address" class="col-sm-3 col-form-label">sijil upsr</label>
      <div class="col-sm-9">
        <div class="custom-file">
          <input name='sijil_pmr' type="file" class="custom-file-input" id="customFile">
          <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
      </div>
    </div>


   
  </div>
  <div class="card-footer text-center">
    <button  data-status='simpan' type="button" class="btnSubmitStudent btn btn-primary">Simpan</button>
    <button  data-status='hantar' type="button" class="btnSubmitStudent btn btn-primary">Simpan</button>
  </div>
</form>
</div>

  @endsection

 @section('scripts')
 <script>
 $(document).on('change', '.custom-file-input', function() {

  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});

</script>

  
@section('scripts')

<script>



$( document ).ready(function() {

  $( ".btnSubmitStudent" ).click(function(e) {

    e.preventDefault();

    var form=$( "#fromstudent" );

  var status=  $(this).data('status');

  var input = $("<input>")
               .attr("type", "hidden")
               .attr("name", "status").val(status);
               form.append(input);


    Swal.fire({
  title: 'Do you want to save the changes?',
  showDenyButton: true,
  showCancelButton: true,
  confirmButtonText: 'Save',
  denyButtonText: `Don't save`,
}).then((result) => {
  /* Read more about isConfirmed, isDenied below */
  if (result.isConfirmed) {

       
      Swal.fire({
       
        icon: 'info',
        title: 'sila tunggun',
        showConfirmButton: false,
     
      })

    form.submit();
  } else if (result.isDenied) {
    Swal.fire('Changes are not saved', '', 'info')
  }
})

   

});


});
</script>



    
@endsection

resources/views/student/edit.blade.php
@extends('layouts.app')


@section('content')

<div class="card">
    <div class="card-header">
        <h4>Horizontal Form</h4>
    </div>
    @php
    print_r($errors->all());
    @endphp


@include('student._form')
    
</div>

@endsection

resources/views/student/editold.blade.php
@extends('layouts.app')


@section('content')

<div class="card">
    <div class="card-header">
        <h4>Horizontal Form</h4>
    </div>
    @php
    print_r($errors->all());
    @endphp


    <form action="{{ route('pelajar.update',['pelajar'=>$student->id]) }}" method="post" enctype="multipart/form-data">
        @method('put')
        @csrf
        <div class="card-body">

            <div class="form-group row">
                <label for="id_name_student" class="col-sm-3 col-form-label">Nama</label>
                <div class="col-sm-9">
                    <input value='{{ old('name_student',$student->name_student??'') }}' name='name_student' type="text"
                        class="form-control @error('name_student') is-invalid @enderror" id="id_name_student"
                        placeholder="Email">
                    @error('name_student')
                    <div class='invalid-feedback'>{{ $message }}</div>
                    @enderror

                </div>
            </div>

            <div class="form-group row">
                <label for="id_ic" class="col-sm-3 col-form-label">IC</label>
                <div class="col-sm-9">
                    <input value='{{ old('ic',$student->ic??'') }}' name='ic' type="text" class="form-control"
                        id="id_ic" placeholder="Email">
                </div>
            </div>

            <div class="form-group row">
                <label for="address" class="col-sm-3 col-form-label">Alamat</label>
                <div class="col-sm-9">
                    <textarea class="form-control" name="address" id="address" cols="30"
                        rows="10">{{ old('address',$student->address??'') }}</textarea>

                    {{-- <input value='{{ old('address',$student->address??'') }}' name='address' type="text"
                    class="form-control" id="address" placeholder="Email"> --}}
                </div>
            </div>

            <div class="form-group row">
                <label for="id_school" class="col-sm-3 col-form-label">Sekolah</label>
                <div class="col-sm-9">
                    <select name='id_school' class="form-control" id="id_school">
                        <option value="" selected>Sila Pilih</option>
                        @if ($lookupSchool??'')
                        @foreach ($lookupSchool as $idsc=>$school)
                        <option {{ old('id_school',$student->id_school??'')==$idsc?'Selected':'' }} value="{{ $idsc }}">
                            {{ $school }}</option>
                        @endforeach

                        @endif
                    </select>
                </div>
            </div>


            <div class="form-group row">
                <label for="id_level" class="col-sm-3 col-form-label">Tahap</label>
                <div class="col-sm-9">
                    <select name='id_level' class="form-control" id="id_level">
                        <option value="" selected>Sila Pilih</option>
                        @if ($lookupLevel??'')
                        @foreach ($lookupLevel as $idlvl=>$level)
                        <option {{ old('id_level',$student->id_level??'')==$idlvl?'Selected':'' }} value="{{ $idlvl }}">
                            {{ $level }}</option>
                        @endforeach

                        @endif
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="address" class="col-sm-3 col-form-label">sijil upsr</label>
                <div class="col-sm-9">
                    <div class="custom-file">
                        <input name='sijil_pmr' type="file" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                    <div>
                    @if ($student->ic_path)

                    <a href="{{ route('downloadfile',['id'=>$student->id]) }}">download by id</a>
                    <br>

                    <a href="{{ route('download.path',['path'=>$student->ic_path]) }}">download by path</a>

                    

                    @endif
                  </div>
                </div>
            </div>




        </div>
        <div class="card-footer text-center">
            <button type="submit" class="btn btn-primary">Simpan</button>
        </div>
    </form>
</div>

@endsection

resources/views/student/index.blade.php
@php
use App\Helpers\BankStatusHelper;
@endphp

@extends('layouts.app')


@section('content')
<div class='col-12'>
<div class="card">
    <form action="{{ route('pelajar.index') }}">

        <div class="card-body">
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-3 col-form-label">Nama</label>
                <div class="col-sm-9">
                    <input name='name_student' type="text" class="form-control" id="inputEmail3" placeholder="Nama">
                </div>
            </div>
{{-- ini utk select school --}}
            <div class="form-group row">
                <label for="id_school" class="col-sm-3 col-form-label">Sekolah</label>
                <div class="col-sm-9">
                    <select name='id_school' class="form-control" id="id_school">
                        <option value="" selected>Sila Pilih</option>
                        @if ($lookupSchool)
                        @foreach ($lookupSchool as $idsc=>$school)
                        <option value="{{ $idsc }}">{{ $school }}</option>
                        @endforeach

                        @endif
                    </select>
                </div>
            </div>
{{-- end select school --}}
            <div class="card-footer text-center">
                <button type="submit" class="btn btn-primary">cari</button>
            </div>

        </div>
    </form>
    
    <div class="card-body">
      <div class='table-responsive'>

        <div class="text-right">
            <a class="btn btn-primary" href="{{ route('pelajar.create') }}">Tambah</a>
        </div>


        <table class='table table-bordered'>
            <tr>
                <th>Bil</th>
                <th>Nama</th>
                <th>Sekolah</th>
                <th>Tahap</th>
                <th>Tindakan</th>
            </tr>
            @php
             
                $bil=BankStatusHelper::countFrom($students);
            @endphp

            @foreach ($students as $student)
            <tr>
                <td>{{ ++$bil }}</td>
                <td>{{ $student->name_student }}</td>
                <td>{{ $student->lookupSchool->name }}</td>
                <td>{{ $student->lookupLevel->name }}</td>
                <td>
                  <div class="btn-group" role="group" aria-label="Basic example">
                  <a href="{{ route('pelajar.show',['pelajar'=>$student->id]) }}" class="btn btn-primary mr-1"><i class="fas fa-file"></i></a>
                  <a href="{{ route('pelajar.edit',['pelajar'=>$student->id]) }}" class="btn btn-info mr-1"><i class="fas fa-edit"></i></a>
                  {{-- <a href="{{ route() }}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a> --}}
                  <form  method='post' action="{{ route('pelajar.destroy',['pelajar'=>$student->id]) }}">
                    @csrf
                    @method('delete')
                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i></button>
                  </form>
                </div>
                
                </td>
            </tr>
            @endforeach

        </table>
      </div>
    </div>
      <div class='card-footer text-right'>
   
          {{ $students->appends(Request::all())->links() }}
    
        
    </div>
</div>
</div>
@endsection

resources/views/student/show.blade.php
@extends('layouts.app')


@section('content')





<div class='card'>
    <div class="card-body">

       Name: {{ $student->name_student }}

    </div>
</div>


@endsection

@section('scripts')

<script>

@if (session('success'))
    
Swal.fire(
  'Good job!',
  '{{ session('success') }}',
  'success'
)


@endif

</script>
    
@endsection